import { AboutStyling } from "../styles/About";
import Link from "next/link";
import Footer from "./components/Footer";
import ArrowUp from "./images/arrow-up.svg";
import Image from "next/image";
import Header from "./components/Header";
import { motion } from "framer-motion";
import { HomeStyling } from "../styles/Home";
import Head from "next/head";

function About() {
  return (
    <AboutStyling>
      <Head>
        <title>Viktor Holik portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="main">
          <div className="container">
            <div className="main__title">
              A 17-years old developer with a sense of company strategy and an
              adaptive approach to{" "}
              <span className="highlight">problem solving.</span>
            </div>
            <div className="button-wrapper">
              <a href="mailto:1viktorholik@gmail.com?subject=Hey Viktor, I want to propose you a work">
                <button className="button">hire me</button>
              </a>
              <a
                href="https://www.linkedin.com/in/viktorholik/"
                target="_blank"
                rel="noreferrer"
              >
                <button className="button">linkedIn</button>
              </a>
            </div>
          </div>
        </div>
      </main>
      <section id="about">
        <div className="container">
          <p className="about-text">
            <div className="line">
              <div className="space"></div>
              <div className="line-inner">
                I divide large and complex tasks into
              </div>
            </div>
            <div className="line">
              self-sufficient and trasparent stages according tocore
              competencies. After that, I combine them for the maximum possible
              result into asingle system
            </div>
          </p>
          <div className="about-subtitle">
            The design is based on deep immersion in the project, painstaking
            analysing of your niche and user needs, But that is not all
            <div className="resume-link">
              Download my resume
              <Image src={ArrowUp} alt="Download resume" />
            </div>
          </div>
          <div className="photo"></div>
        </div>
      </section>
      <Footer />
    </AboutStyling>
  );
}

export default About;
