import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { HomeStyling } from "../styles/Home";
import ArrowRight from "./images/arrow-right.svg";
import Footer from "./components/Footer";
import gsap from "gsap";
import { useEffect, useRef } from "react";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
import Link from "next/link";
import Header from "./components/Header";
import cases from "../cases";

const Home: NextPage = () => {
  const highlightSection = useRef(null);
  const highlightText = useRef(null);
  const introSection = useRef(null);
  useEffect(() => {
    const tlIntro = gsap.timeline({
      scrollTrigger: {
        trigger: introSection.current,
        start: "0%",
        end: "100%",
        pin: true,
        pinSpacing: false,
      },
    });

    const tlH = gsap.timeline({
      scrollTrigger: {
        trigger: highlightSection.current,
        // markers: { startColor: "white", endColor: "white" },
        scrub: true,
        start: "-40%",
        end: "60%",
      },
    });
    tlH.fromTo(
      ".highlight",
      {
        color: "rgba(255,255,255,0.1)",
      },
      {
        color: "rgba(255,255,255,1)",
        stagger: 1,
      }
    );
    // Remove
    const tlHRemove = gsap.timeline({
      scrollTrigger: {
        trigger: highlightSection.current,
        // markers: { startColor: "white", endColor: "white" },
        scrub: true,
        start: "-20%",
        end: "80%",
      },
    });

    tlHRemove.to(".highlight", {
      color: "rgba(255,255,255,0.1)",
      stagger: 1,
    });
  }, []);

  return (
    <HomeStyling>
      <Head>
        <title>Viktor Holik portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={introSection}>
        <video className="video-wrapper" autoPlay loop muted>
          <source src="http://localhost:3000/tunel.mp4" type="video/mp4" />
        </video>
        <Header />
        <div className="main">
          <div className="container">
            <h1 className="main__title">
              Engeering aesthetics of digital world
            </h1>
          </div>
        </div>
        <div className="navbar">
          <div className="container">
            <div className="navbar__wrapper">
              <div className="navbar-item">
                <p className="link">(Hire me)</p>
              </div>
              <div className="navbar-item">
                <p className="navbar-item__header">Contact me</p>
                <div className="right">
                  <p className="link">project@viktorholik.com</p>
                  <p className="link">via: linked in</p>
                </div>
              </div>
              <div className="navbar-item">
                <p className="navbar-item__header">About me</p>
                <div className="right">
                  <p className="about-me">
                    Front-end developer with experience in React + Redux
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      {/* About */}
      <section id="body">
        <div className="about">
          <div className="container">
            <h1 className="about__text">
              Hello, world! I&rsquo;m Viktor Holik, a developer specializing in
              React and user interface design. I enjoy creating meaningful
              narratives through smart design and experimenting with new
              technologies
            </h1>
            <div className="about__link">
              <p>More about me</p>
              <Image src={ArrowRight} height={25} width={25} alt="Arrow" />
            </div>
          </div>
        </div>
        <div className="work">
          <div className="container">
            <div className="header">
              <div className="header__title">(Recent work)</div>
              <div className="header__link">
                <p>See all</p>
                <Image src={ArrowRight} height={25} width={25} alt="Arrow" />
              </div>
            </div>
            <div className="work-wrapper">
              {cases.slice(0, 3).map((work, index) => (
                <Link href={`/works/${work.id}`} key={index}>
                  <div
                    className="case"
                    key={index}
                    style={{
                      backgroundImage: `url(${work.images[0].src})`,
                      backgroundPosition: "center",
                      backgroundSize: "cover",
                      backgroundRepeat: "no-repeat",
                    }}
                  >
                    <div className="tags-wrapper">
                      {work.tags.map((tag, index) => (
                        <button className="tag" key={index}>
                          {tag}
                        </button>
                      ))}
                    </div>
                    <h2 className="case__title">{work.name}</h2>
                  </div>
                </Link>
              ))}
            </div>
            <button className="all-works-btn">All works</button>
          </div>
        </div>
        {/* Animated Text */}
        <div className="highlighted-text-section" ref={highlightSection}>
          <div className="container">
            <h1 className="animated-text" ref={highlightText}>
              <span className="highlight">I Integrate, </span>
              <span className="highlight">collaborate and challange. </span>
              <span className="highlight">I am digital native </span>
              <span className="highlight">embracing the creative freedom </span>
              <span className="highlight">to produce solutions </span>{" "}
              <span className="highlight">to connect, communicate, </span>
              <span className="highlight">and inspire...</span>
            </h1>
          </div>
        </div>
        <div className="cover"></div>
      </section>
      <Footer />
    </HomeStyling>
  );
};

export default Home;
