import Link from "next/link";
import { WorksStyling } from "../styles/Works";
import Header from "./components/Header";
import Cases from "../cases";
import Footer from "./components/Footer";
import { motion } from "framer-motion";
import Head from "next/head";

function Works() {
  return (
    <WorksStyling>
      <Head>
        <title>Viktor Holik portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="main">
          <div className="container">
            <div className="main__title">
              Purpose driven, strategy-led presentations that{" "}
              <span className="highlight">people care about.</span>
            </div>
            <div className="button-wrapper">
              <a href="mailto:1viktorholik@gmail.com?subject=Hey Viktor, I want to propose you a work">
                <button className="button">hire me</button>
              </a>
              <a
                href="https://www.linkedin.com/in/viktorholik/"
                target="_blank"
                rel="noreferrer"
              >
                <button className="button">linkedIn</button>
              </a>
            </div>
          </div>
        </div>
      </main>
      <section className="work-wrapper">
        <div className="container">
          <div className="work-inner">
            {Cases.map((work, index) => (
              <Link href={`/works/${work.id}`} key={index}>
                <div className="work-item" key={index}>
                  <div className="left">
                    <div
                      className="case-image"
                      style={{
                        backgroundImage: `url(${work.images[0].src})`,
                        backgroundPosition: "center",
                        backgroundSize: "cover",
                        backgroundRepeat: "no-repeat",
                      }}
                    ></div>
                  </div>
                  <div className="right">
                    <div className="top">({work.year})</div>
                    <div className="bottom">
                      <div className="tags-wrapper">
                        {work.tags.map((tag, index) => (
                          <div key={index} className="tag">
                            {tag}
                          </div>
                        ))}
                      </div>
                      <div className="case-title">{work.name}</div>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>
      <Footer />
    </WorksStyling>
  );
}

export default Works;
